'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4200
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace WCFDebugService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DebugScriptInfo", [Namespace]:="http://schemas.datacontract.org/2004/07/xPLHalDebugger"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DebugScriptInfo
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private GlobalScriptSourceField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HalIPAddressField As System.Net.IPAddress
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ScriptNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SourceField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SourceFileField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private xPLMessageStringField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property GlobalScriptSource() As String
            Get
                Return Me.GlobalScriptSourceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.GlobalScriptSourceField, value) <> true) Then
                    Me.GlobalScriptSourceField = value
                    Me.RaisePropertyChanged("GlobalScriptSource")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property HalIPAddress() As System.Net.IPAddress
            Get
                Return Me.HalIPAddressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.HalIPAddressField, value) <> true) Then
                    Me.HalIPAddressField = value
                    Me.RaisePropertyChanged("HalIPAddress")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ScriptName() As String
            Get
                Return Me.ScriptNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ScriptNameField, value) <> true) Then
                    Me.ScriptNameField = value
                    Me.RaisePropertyChanged("ScriptName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Source() As String
            Get
                Return Me.SourceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SourceField, value) <> true) Then
                    Me.SourceField = value
                    Me.RaisePropertyChanged("Source")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SourceFile() As String
            Get
                Return Me.SourceFileField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SourceFileField, value) <> true) Then
                    Me.SourceFileField = value
                    Me.RaisePropertyChanged("SourceFile")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property xPLMessageString() As String
            Get
                Return Me.xPLMessageStringField
            End Get
            Set
                If (Object.ReferenceEquals(Me.xPLMessageStringField, value) <> true) Then
                    Me.xPLMessageStringField = value
                    Me.RaisePropertyChanged("xPLMessageString")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WCFDebugService.IWCFDebugService")>  _
    Public Interface IWCFDebugService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWCFDebugService/SetDebugScriptInfo", ReplyAction:="http://tempuri.org/IWCFDebugService/SetDebugScriptInfoResponse")>  _
        Sub SetDebugScriptInfo(ByRef info As WCFDebugService.DebugScriptInfo)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface IWCFDebugServiceChannel
        Inherits WCFDebugService.IWCFDebugService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class WCFDebugServiceClient
        Inherits System.ServiceModel.ClientBase(Of WCFDebugService.IWCFDebugService)
        Implements WCFDebugService.IWCFDebugService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub SetDebugScriptInfo(ByRef info As WCFDebugService.DebugScriptInfo) Implements WCFDebugService.IWCFDebugService.SetDebugScriptInfo
            MyBase.Channel.SetDebugScriptInfo(info)
        End Sub
    End Class
End Namespace
