'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4918
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("xPLHalMgr.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang2057\deflangfe2057{\fonttbl{\f0\fswiss\fcharset0 Arial;}{\f1\fswiss\fprq2\fcharset0 Arial;}{\f2\froman\fprq2\fcharset0 Times New Roman;}}
        '''{\colortbl ;\red0\green0\blue255;}
        '''\viewkind4\uc1\pard\nowidctlpar\li360\qc\tx720\f0\fs20{\pict\wmetafile8\picw1667\pich1667\picwgoal945\pichgoal945 
        '''010009000003480b00000000020a000000000400000003010800050000000b0200000000050000
        '''000c023f003f000500000007010400000022010000430f8600ee0000003f003f00000000003f00
        '''3f0000000000280000003f00 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property homepage() As String
            Get
                Return ResourceManager.GetString("homepage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;About.
        '''</summary>
        Friend ReadOnly Property RES_ABOUT() As String
            Get
                Return ResourceManager.GetString("RES_ABOUT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add.
        '''</summary>
        Friend ReadOnly Property RES_ADD() As String
            Get
                Return ResourceManager.GetString("RES_ADD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address.
        '''</summary>
        Friend ReadOnly Property RES_ADDRESS() As String
            Get
                Return ResourceManager.GetString("RES_ADDRESS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All.
        '''</summary>
        Friend ReadOnly Property RES_ALL() As String
            Get
                Return ResourceManager.GetString("RES_ALL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Awaiting Configuration.
        '''</summary>
        Friend ReadOnly Property RES_AWAITING_CONFIG() As String
            Get
                Return ResourceManager.GetString("RES_AWAITING_CONFIG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend ReadOnly Property RES_CANCEL() As String
            Get
                Return ResourceManager.GetString("RES_CANCEL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This script cannot be deleted because it is required for successful operation of xPLHal..
        '''</summary>
        Friend ReadOnly Property RES_CANNOT_DEL_SCRIPT() As String
            Get
                Return ResourceManager.GetString("RES_CANNOT_DEL_SCRIPT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change Server.
        '''</summary>
        Friend ReadOnly Property RES_CHANGE_SERVER() As String
            Get
                Return ResourceManager.GetString("RES_CHANGE_SERVER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Check for Updates.
        '''</summary>
        Friend ReadOnly Property RES_CHECK_UPDATES() As String
            Get
                Return ResourceManager.GetString("RES_CHECK_UPDATES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clear.
        '''</summary>
        Friend ReadOnly Property RES_CLEAR() As String
            Get
                Return ResourceManager.GetString("RES_CLEAR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to clear the xPLHal Error Log?.
        '''</summary>
        Friend ReadOnly Property RES_CLEAR_ERROR_LOG() As String
            Get
                Return ResourceManager.GetString("RES_CLEAR_ERROR_LOG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Configure Device.
        '''</summary>
        Friend ReadOnly Property RES_CONFIG() As String
            Get
                Return ResourceManager.GetString("RES_CONFIG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter the name of your xPLHal server:.
        '''</summary>
        Friend ReadOnly Property RES_CONNECT_SERVER() As String
            Get
                Return ResourceManager.GetString("RES_CONNECT_SERVER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copy.
        '''</summary>
        Friend ReadOnly Property RES_COPY() As String
            Get
                Return ResourceManager.GetString("RES_COPY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Current Value.
        '''</summary>
        Friend ReadOnly Property RES_CURRENTVALUE() As String
            Get
                Return ResourceManager.GetString("RES_CURRENTVALUE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cut.
        '''</summary>
        Friend ReadOnly Property RES_CUT() As String
            Get
                Return ResourceManager.GetString("RES_CUT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date/Time.
        '''</summary>
        Friend ReadOnly Property RES_DATETIME() As String
            Get
                Return ResourceManager.GetString("RES_DATETIME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete Stored Configuration.
        '''</summary>
        Friend ReadOnly Property RES_DEL_CONFIG() As String
            Get
                Return ResourceManager.GetString("RES_DEL_CONFIG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Determinator.
        '''</summary>
        Friend ReadOnly Property RES_DETERMINATOR() As String
            Get
                Return ResourceManager.GetString("RES_DETERMINATOR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Determinator Name.
        '''</summary>
        Friend ReadOnly Property RES_DETERMINATORNAME() As String
            Get
                Return ResourceManager.GetString("RES_DETERMINATORNAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Determinators.
        '''</summary>
        Friend ReadOnly Property RES_DETERMINATORS() As String
            Get
                Return ResourceManager.GetString("RES_DETERMINATORS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Device.
        '''</summary>
        Friend ReadOnly Property RES_DEVICE() As String
            Get
                Return ResourceManager.GetString("RES_DEVICE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Device Name.
        '''</summary>
        Friend ReadOnly Property RES_DEVICENAME() As String
            Get
                Return ResourceManager.GetString("RES_DEVICENAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit.
        '''</summary>
        Friend ReadOnly Property RES_EDIT() As String
            Get
                Return ResourceManager.GetString("RES_EDIT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit XML Configuration.
        '''</summary>
        Friend ReadOnly Property RES_EDIT_CONFIG() As String
            Get
                Return ResourceManager.GetString("RES_EDIT_CONFIG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enable filter.
        '''</summary>
        Friend ReadOnly Property RES_ENABLE_FILTER() As String
            Get
                Return ResourceManager.GetString("RES_ENABLE_FILTER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could not connect to xPLHal.
        '''
        '''Make sure that xPLHal is running on the target computer..
        '''</summary>
        Friend ReadOnly Property RES_ERROR_CONNECT() As String
            Get
                Return ResourceManager.GetString("RES_ERROR_CONNECT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Event.
        '''</summary>
        Friend ReadOnly Property RES_EVENT() As String
            Get
                Return ResourceManager.GetString("RES_EVENT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must enter a name for this event..
        '''</summary>
        Friend ReadOnly Property RES_EVENT_ENTER_NAME() As String
            Get
                Return ResourceManager.GetString("RES_EVENT_ENTER_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to save the changes you made to this event?.
        '''</summary>
        Friend ReadOnly Property RES_EVENT_SAVE_CHANGES() As String
            Get
                Return ResourceManager.GetString("RES_EVENT_SAVE_CHANGES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Event Name.
        '''</summary>
        Friend ReadOnly Property RES_EVENTNAME() As String
            Get
                Return ResourceManager.GetString("RES_EVENTNAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Events.
        '''</summary>
        Friend ReadOnly Property RES_EVENTS() As String
            Get
                Return ResourceManager.GetString("RES_EVENTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to E&amp;xit.
        '''</summary>
        Friend ReadOnly Property RES_EXIT() As String
            Get
                Return ResourceManager.GetString("RES_EXIT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Expires.
        '''</summary>
        Friend ReadOnly Property RES_EXPIRES() As String
            Get
                Return ResourceManager.GetString("RES_EXPIRES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;File.
        '''</summary>
        Friend ReadOnly Property RES_FILE() As String
            Get
                Return ResourceManager.GetString("RES_FILE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Filter.
        '''</summary>
        Friend ReadOnly Property RES_FILTER() As String
            Get
                Return ResourceManager.GetString("RES_FILTER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Filter Options.
        '''</summary>
        Friend ReadOnly Property RES_FILTER_OPTIONS() As String
            Get
                Return ResourceManager.GetString("RES_FILTER_OPTIONS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Global Name.
        '''</summary>
        Friend ReadOnly Property RES_GLOBALNAME() As String
            Get
                Return ResourceManager.GetString("RES_GLOBALNAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Globals.
        '''</summary>
        Friend ReadOnly Property RES_GLOBALS() As String
            Get
                Return ResourceManager.GetString("RES_GLOBALS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Help.
        '''</summary>
        Friend ReadOnly Property RES_HELP() As String
            Get
                Return ResourceManager.GetString("RES_HELP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Help Topics.
        '''</summary>
        Friend ReadOnly Property RES_HELP_TOPICS() As String
            Get
                Return ResourceManager.GetString("RES_HELP_TOPICS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hop.
        '''</summary>
        Friend ReadOnly Property RES_HOP() As String
            Get
                Return ResourceManager.GetString("RES_HOP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Instance.
        '''</summary>
        Friend ReadOnly Property RES_INSTANCE() As String
            Get
                Return ResourceManager.GetString("RES_INSTANCE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select your preferred language.
        '''</summary>
        Friend ReadOnly Property RES_LANGUAGE() As String
            Get
                Return ResourceManager.GetString("RES_LANGUAGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select Language.
        '''</summary>
        Friend ReadOnly Property RES_LANGUAGE_CAPTION() As String
            Get
                Return ResourceManager.GetString("RES_LANGUAGE_CAPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Messages.
        '''</summary>
        Friend ReadOnly Property RES_MESSAGES() As String
            Get
                Return ResourceManager.GetString("RES_MESSAGES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must select a sub-routine to be executed..
        '''</summary>
        Friend ReadOnly Property RES_MUST_SELECT_SUB() As String
            Get
                Return ResourceManager.GetString("RES_MUST_SELECT_SUB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New.
        '''</summary>
        Friend ReadOnly Property RES_NEW() As String
            Get
                Return ResourceManager.GetString("RES_NEW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Global Variable.
        '''</summary>
        Friend ReadOnly Property RES_NEW_GLOBAL() As String
            Get
                Return ResourceManager.GetString("RES_NEW_GLOBAL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Determinator.
        '''</summary>
        Friend ReadOnly Property RES_NEW_RULE() As String
            Get
                Return ResourceManager.GetString("RES_NEW_RULE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New X10 Device.
        '''</summary>
        Friend ReadOnly Property RES_NEW_X10() As String
            Get
                Return ResourceManager.GetString("RES_NEW_X10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Next Run Time.
        '''</summary>
        Friend ReadOnly Property RES_NEXTRUNTIME() As String
            Get
                Return ResourceManager.GetString("RES_NEXTRUNTIME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to None.
        '''</summary>
        Friend ReadOnly Property RES_NONE() As String
            Get
                Return ResourceManager.GetString("RES_NONE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Friend ReadOnly Property RES_OK() As String
            Get
                Return ResourceManager.GetString("RES_OK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Paste.
        '''</summary>
        Friend ReadOnly Property RES_PASTE() As String
            Get
                Return ResourceManager.GetString("RES_PASTE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to delete the determinator %1?.
        '''</summary>
        Friend ReadOnly Property RES_PROMPT_DEL_DETERMINATOR() As String
            Get
                Return ResourceManager.GetString("RES_PROMPT_DEL_DETERMINATOR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to delete the script %1?.
        '''</summary>
        Friend ReadOnly Property RES_PROMPT_DEL_SCRIPT() As String
            Get
                Return ResourceManager.GetString("RES_PROMPT_DEL_SCRIPT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Properties.
        '''</summary>
        Friend ReadOnly Property RES_PROPERTIES() As String
            Get
                Return ResourceManager.GetString("RES_PROPERTIES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Recurring.
        '''</summary>
        Friend ReadOnly Property RES_RECURRING() As String
            Get
                Return ResourceManager.GetString("RES_RECURRING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Refresh.
        '''</summary>
        Friend ReadOnly Property RES_REFRESH() As String
            Get
                Return ResourceManager.GetString("RES_REFRESH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reload Scripts.
        '''</summary>
        Friend ReadOnly Property RES_RELOAD() As String
            Get
                Return ResourceManager.GetString("RES_RELOAD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You have made changes to one or more scripts.
        '''
        '''Do you want to reload all scripts now?.
        '''</summary>
        Friend ReadOnly Property RES_RELOAD_NOW() As String
            Get
                Return ResourceManager.GetString("RES_RELOAD_NOW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Restart xPLHal Service.
        '''</summary>
        Friend ReadOnly Property RES_RESTART() As String
            Get
                Return ResourceManager.GetString("RES_RESTART", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Run Sub-routine.
        '''</summary>
        Friend ReadOnly Property RES_RUN_SUB() As String
            Get
                Return ResourceManager.GetString("RES_RUN_SUB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Save.
        '''</summary>
        Friend ReadOnly Property RES_SAVE() As String
            Get
                Return ResourceManager.GetString("RES_SAVE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to save the changes you made to %1?.
        '''</summary>
        Friend ReadOnly Property RES_SAVE_CHANGES() As String
            Get
                Return ResourceManager.GetString("RES_SAVE_CHANGES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save and &amp;Reload.
        '''</summary>
        Friend ReadOnly Property RES_SAVE_RELOAD() As String
            Get
                Return ResourceManager.GetString("RES_SAVE_RELOAD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Schema.
        '''</summary>
        Friend ReadOnly Property RES_SCHEMA() As String
            Get
                Return ResourceManager.GetString("RES_SCHEMA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Script.
        '''</summary>
        Friend ReadOnly Property RES_SCRIPT() As String
            Get
                Return ResourceManager.GetString("RES_SCRIPT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Script Name.
        '''</summary>
        Friend ReadOnly Property RES_SCRIPTNAME() As String
            Get
                Return ResourceManager.GetString("RES_SCRIPTNAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scripts.
        '''</summary>
        Friend ReadOnly Property RES_SCRIPTS() As String
            Get
                Return ResourceManager.GetString("RES_SCRIPTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scripts reloaded successfully..
        '''</summary>
        Friend ReadOnly Property RES_SCRIPTS_RELOADED() As String
            Get
                Return ResourceManager.GetString("RES_SCRIPTS_RELOADED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scripts could not be reloaded.
        '''
        '''Please review any changes you have made recently and correct any errors.
        '''
        '''Do you want to view the error log?.
        '''</summary>
        Friend ReadOnly Property RES_SCRIPTS_RELOADED_ERROR() As String
            Get
                Return ResourceManager.GetString("RES_SCRIPTS_RELOADED_ERROR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select Language.
        '''</summary>
        Friend ReadOnly Property RES_SELECT_LANGUAGE() As String
            Get
                Return ResourceManager.GetString("RES_SELECT_LANGUAGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Send xPL Message.
        '''</summary>
        Friend ReadOnly Property RES_SEND_XPL() As String
            Get
                Return ResourceManager.GetString("RES_SEND_XPL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Single.
        '''</summary>
        Friend ReadOnly Property RES_SINGLE() As String
            Get
                Return ResourceManager.GetString("RES_SINGLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Source.
        '''</summary>
        Friend ReadOnly Property RES_SOURCE() As String
            Get
                Return ResourceManager.GetString("RES_SOURCE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start.
        '''</summary>
        Friend ReadOnly Property RES_START() As String
            Get
                Return ResourceManager.GetString("RES_START", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to State.
        '''</summary>
        Friend ReadOnly Property RES_STATE() As String
            Get
                Return ResourceManager.GetString("RES_STATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stats.
        '''</summary>
        Friend ReadOnly Property RES_STATS() As String
            Get
                Return ResourceManager.GetString("RES_STATS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stop.
        '''</summary>
        Friend ReadOnly Property RES_STOP() As String
            Get
                Return ResourceManager.GetString("RES_STOP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Execute.
        '''</summary>
        Friend ReadOnly Property RES_SUBROUTINE() As String
            Get
                Return ResourceManager.GetString("RES_SUBROUTINE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Target.
        '''</summary>
        Friend ReadOnly Property RES_TARGET() As String
            Get
                Return ResourceManager.GetString("RES_TARGET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Time.
        '''</summary>
        Friend ReadOnly Property RES_TIME() As String
            Get
                Return ResourceManager.GetString("RES_TIME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to xPLHal Manager.
        '''</summary>
        Friend ReadOnly Property RES_TITLE() As String
            Get
                Return ResourceManager.GetString("RES_TITLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to About.
        '''</summary>
        Friend ReadOnly Property RES_TOOLBAR_ABOUT() As String
            Get
                Return ResourceManager.GetString("RES_TOOLBAR_ABOUT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change Server.
        '''</summary>
        Friend ReadOnly Property RES_TOOLBAR_CHANGESERVER() As String
            Get
                Return ResourceManager.GetString("RES_TOOLBAR_CHANGESERVER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Help.
        '''</summary>
        Friend ReadOnly Property RES_TOOLBAR_HELP() As String
            Get
                Return ResourceManager.GetString("RES_TOOLBAR_HELP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Monitor.
        '''</summary>
        Friend ReadOnly Property RES_TOOLBAR_MONITOR() As String
            Get
                Return ResourceManager.GetString("RES_TOOLBAR_MONITOR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New....
        '''</summary>
        Friend ReadOnly Property RES_TOOLBAR_NEW() As String
            Get
                Return ResourceManager.GetString("RES_TOOLBAR_NEW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Refresh.
        '''</summary>
        Friend ReadOnly Property RES_TOOLBAR_REFRESH() As String
            Get
                Return ResourceManager.GetString("RES_TOOLBAR_REFRESH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reload Scripts.
        '''</summary>
        Friend ReadOnly Property RES_TOOLBAR_RELOAD() As String
            Get
                Return ResourceManager.GetString("RES_TOOLBAR_RELOAD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Run Determinator.
        '''</summary>
        Friend ReadOnly Property RES_TOOLBAR_RUNDET() As String
            Get
                Return ResourceManager.GetString("RES_TOOLBAR_RUNDET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Run Subroutine.
        '''</summary>
        Friend ReadOnly Property RES_TOOLBAR_RUNSUB() As String
            Get
                Return ResourceManager.GetString("RES_TOOLBAR_RUNSUB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Send xPL Message.
        '''</summary>
        Friend ReadOnly Property RES_TOOLBAR_SENDXPL() As String
            Get
                Return ResourceManager.GetString("RES_TOOLBAR_SENDXPL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Turn X10 device off.
        '''</summary>
        Friend ReadOnly Property RES_TOOLBAR_X10OFF() As String
            Get
                Return ResourceManager.GetString("RES_TOOLBAR_X10OFF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Turn X10 device on.
        '''</summary>
        Friend ReadOnly Property RES_TOOLBAR_X10ON() As String
            Get
                Return ResourceManager.GetString("RES_TOOLBAR_X10ON", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Tools.
        '''</summary>
        Friend ReadOnly Property RES_TOOLS() As String
            Get
                Return ResourceManager.GetString("RES_TOOLS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Type.
        '''</summary>
        Friend ReadOnly Property RES_TYPE() As String
            Get
                Return ResourceManager.GetString("RES_TYPE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Update Plug-in Library.
        '''</summary>
        Friend ReadOnly Property RES_UPDATE_PLUGINS() As String
            Get
                Return ResourceManager.GetString("RES_UPDATE_PLUGINS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vendor.
        '''</summary>
        Friend ReadOnly Property RES_VENDOR() As String
            Get
                Return ResourceManager.GetString("RES_VENDOR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;View.
        '''</summary>
        Friend ReadOnly Property RES_VIEW() As String
            Get
                Return ResourceManager.GetString("RES_VIEW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to View Error Log.
        '''</summary>
        Friend ReadOnly Property RES_VIEW_ERROR() As String
            Get
                Return ResourceManager.GetString("RES_VIEW_ERROR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to View Script.
        '''</summary>
        Friend ReadOnly Property RES_VIEW_SCRIPT() As String
            Get
                Return ResourceManager.GetString("RES_VIEW_SCRIPT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to X10 Device.
        '''</summary>
        Friend ReadOnly Property RES_X10() As String
            Get
                Return ResourceManager.GetString("RES_X10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to xPL Devices.
        '''</summary>
        Friend ReadOnly Property RES_XPL_DEVICES() As String
            Get
                Return ResourceManager.GetString("RES_XPL_DEVICES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to xPL Messages Received.
        '''</summary>
        Friend ReadOnly Property RES_XPLMESSAGES_RECEIVED() As String
            Get
                Return ResourceManager.GetString("RES_XPLMESSAGES_RECEIVED", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
